# Site settings
title: isnoopytokky blog
email: 
description: "no one perfect."
baseurl: "http://pariwatram.github.io/isnoopytokky.github.io"
url: "http://isnoopytokky.github.io"
twitter_username: isnoopytokky
github_username:  isnoopytokky

# Build settings
markdown: redcarpet
permalink: pretty
